import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage, } from "next";
import Head from "next/head";
import Image from "next/image";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

import { RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className=" flex gap-3 ">
      <Image className=" h-16 w-16 rounded-full " src={user.profileImageUrl} alt="profile image" width={56} height={56} />
      <input placeholder="Type some emojis!" className=" bg-transparent grow outline-none" />
    </div>
  )
}

type PostWithUser = RouterOutputs['posts']['getAll'][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div className="flex p-4 border-b border-slate-400 gap-3" key={post.id}>
      <Image src={author.profileImageUrl} alt="profile image" width={56} height={56} />
      <div className=" flex flex-col">
        <div className=" flex text-slate-300 font-bold">
          <span>{`@${author.username!} · ${dayjs(post.createdAt).fromNow()}`} </span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>)
}

const Home: NextPage = () => {

  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading ...</div>

  if (!data) return <div>Something went wrong ...</div>

  return (
    <>
      <Head>
        <title>Create T3 App by Victor</title>
        <meta name="description" content="Generated by Victor" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && <div className=" flex justify-center"><SignInButton /></div>}
            {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className=" flex flex-col">
            {data?.map((fullPost) => <PostView {...fullPost} key={fullPost.post.id} />)}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
